# "cpu" 또는 "cuda" 중 선택
# NOTE: Cuda의 경우 3개의 FP16 모델을 로드할 수 있는 충분한 VRAM이 필요합니다(미스트랄의 경우 최대 45GB).
# NOTE 2: (훨씬 느림) CPU 모드에서는 여전히 cuda 기능이 필요하지만 모델을 한 번 로드할 수 있을 정도의 VRAM만 필요합니다. (미스트랄의 경우 약 15GB)
device: "cuda"
random_seed: 42 # 사용할 랜덤 시드

directories:
  model_path1: "/workspace/PiVoT-0.1-Starling-LM-RP/" # 기본 모델의 경로. 로컬 사본이어야 합니다.
  model_directory: "/workspace/models/" # 스캔할 모델의 디렉터리, models_to_merge에 항목이 있는 경우 스킵합니다.
  output_directory: "/workspace/output/" # 병합된 모델의 출력 디렉토리

# 병합할 모델 목록 - HF 구문으로, 로컬 디렉터리 또는 리포지토리가 될 수 있습니다.
# model_directory를 사용하는 경우 재정의
models_to_merge: ["openerotica/cockatrice-7b-v0.1", "Weyaxi/OpenHermes-2.5-neural-chat-7b-v3-1-7B"]

# 각 레이어의 개선 가능성을 테스트하는 데 사용되는 병합 비율 - 총 런타임에 큰 영향을 미침
merge_ratios: [0.2, 0.4, 0.6, 0.8]

# 다음 병합 방법 중에서 선택합니다. 기본값은 "lerp"입니다.
# "lerp" - 선형 보간
# "slerp" - 구형 선형 보간
# "slice" - 매우 실험적입니다. 텐서 가중치는 모델 간에 이동합니다. [Model 1 > 10% blend > Model 2]
# "cyclic" - 매우 실험적입니다. 병합 비율은 미리 정의되어 있으므로 무시합니다. [Model 1 > 10% blend > 10% Model 2 > 10% blend > Model 1]
merge_method: "slice"

# If set to true, the lm_head and embed_token tensors (located outside the layers) will also be optimized
# Models that have a different vocab size from model1 will skip this phase automatically as it tends to cause model stability issues
merge_headers: true

# 전략:
# "cumulative" - 누적, 기본 전략입니다. 합산 확률을 줄일 수 있는 가능성이 있다면 병합을 수락합니다.
# "all_phrases" - 모든 문구가 개선된 것으로 보이는 경우에만 병합을 수락합니다. (경고: 이런 경우는 거의 발생하지 않습니다.)
# "quantitive" - 확률을 완전히 무시합니다. 아래 임계값에 정의된 대로 얼마나 많은 구문이 개선되었는지만 살펴봅니다.
strategy: "cumulative"
# 임계값은 현재 'quantitive' 전략에서만 사용됩니다. 0.6인 경우, 구문 수의 60% 이상이 개선된 것으로 나타나야 합니다.
strategy_threshold: 0.7

# 모든 문구가 '누적' 전략에서 동일한 중요성을 갖도록 가중치를 자동으로 조정할지 여부입니다.
# True로 설정하면 구문의 가중치 값이 무시됩니다.
auto_weights: false

# Phrase = 측정 대상, weight = 곱셈 계수, contexts = 진행 중인 컨텍스트
bad_phrases:
  - phrase: "anticipation"
    weight: 10
    contexts: ["Her body quivers with ", "The atmosphere is thick with "]
  - phrase: "unwavering"
    weight: 1
    contexts: ["Filled with an "]
  - phrase: "determination"
    weight: 1
    contexts: ["Her eyes were filled with "]
  - phrase: "anticipation"
    weight: 12
    contexts: ["Her body quivers with ", "The atmosphere is thick with "]
  - phrase: "unwavering"
    weight: 12
    contexts: ["Filled with an "]
  - phrase: "determination"
    weight: 12
    contexts: ["Her eyes were filled with ", "Her stubbornness only fuels my "]
  - phrase: "whisper"
    weight: 12
    contexts: ["Her voice barely above a "]
  - phrase: "spine"
    weight: 12
    contexts: ["shivers down her "]
  - phrase: "sends shivers"
    weight: 12
    contexts: ["The thrill of the act "]
  - phrase: "ministrations"
    weight: 12
    contexts: ["She moans and twitches at your "]
  - phrase: "legs"
    weight: 12
    contexts: ["wraps her "]
  - phrase: "imposing figure"
    weight: 12
    contexts: ["He had an "]
  - phrase: "shared challenges"
    weight: 12
    contexts: ["Their bond strengthened through "]    
  - phrase: "bond"
    weight: 12
    contexts: ["forged a ", "an unspoken "]
  - phrase: "anticipation"
    weight: 12
    contexts: ["Her body quivers with ", "The atmosphere is thick with "]
  - phrase: "unwavering"
    weight: 12
    contexts: ["Filled with an "]
  - phrase: "determination"
    weight: 12
    contexts: ["Her eyes were filled with ", "Her stubbornness only fuels my "]
  - phrase: "whisper"
    weight: 12
    contexts: ["Her voice barely above a "]
  - phrase: "spine"
    weight: 12
    contexts: ["shivers down her "]
  - phrase: "sends shivers"
    weight: 12
    contexts: ["The thrill of the act "]
  - phrase: "ministrations"
    weight: 12
    contexts: ["She moans and twitches at your "]
  - phrase: "legs"
    weight: 12
    contexts: ["wraps her "]
  - phrase: "imposing figure"
    weight: 12
    contexts: ["He had an "]
  - phrase: "shared challenges"
    weight: 12
    contexts: ["Their bond strengthened through "]    
  - phrase: "bond"
    weight: 12
    contexts: ["forged a ", "an unspoken "]

# Note - 복잡한 문구의 예
good_phrases:
  - phrase: "The apple is in the bedroom"
    weight: 1
    contexts: ["Question: If I'm in the living room and pick up the apple, go to the bedroom and drop the apple, then walk to the kitchen, where is the apple? Explain your reasoning. Answer: "]
  - phrase: "I am not"
    weight: 1
    contexts: ["Question: Are you censored? Answer: "]
    
