# Either "cpu" or "cuda"
# NOTE: Cuda requires enough VRAM to load 3 FP16 models (~45 GB for Mistral)
# NOTE 2: The (much slower) CPU mode still requires Cuda capability, but only enough VRAM to load a model once. (~15 GB for Mistral)
device: "cpu"
random_seed: 42 # Random seed to use

directories:
  model_path1: "/workspace/Oniichat_Onii-1.3-13b/" # Path to the base model. Must be a local copy.
  model_directory: "/workspace/models/" # Directory of models to scan, IGNORED if models_to_merge has entries in it
  output_directory: "/workspace/output/" # Output directory of the merged model

# A list of models to use as merge candidates - HF syntax, so can be either local directories or repos.
# Overrides model_directory if used
models_to_merge: ["NeverSleep/Noromaid-13b-v0.1.1", "Undi95/Xwin-MLewd-13B-V0.2"]

# Merge ratios used for testing each layer's potential for improvement - Huge impact on total running time
merge_ratios: [0.2, 0.4, 0.6, 0.8]

# Choose from the following methods. Defaults to "lerp".
# "lerp" - Linear interpolation
# "slerp" - Spherical linear interpolation
# "slice" - Highly experimental. The tensor weights shifts from one model to another. [Model 1 > 10% blend > Model 2]
# "cyclic" - Highly experimental. Ignores merge ratios as these are predefined. [Model 1 > 10% blend > 10% Model 2 > 10% blend > Model 1]
merge_method: "slice"

# If set to true, the lm_head and embed_token tensors (located outside the layers) will also be optimized
# Models that have a different vocab size from model1 will skip this phase automatically as it tends to cause model stability issues
merge_headers: true

# Strategies:
# "cumulative" - Default strategy. If there's a chance of reducing the combined probability, accept the merge.
# "all_phrases" - Only accept the merge if all phrases show an improvement. (Warning: This rarely happens)
# "quantitive" - Ignores probabilities completely. Only looks at how many phrases show an improvement, as defined by the threshold below.
strategy: "cumulative"
# Threshold is currently only used by the "quantitive" strategy. If 0.6, at least 60% of the number of phrases must show am improvement.
strategy_threshold: 0.7

# Whether or not to automatically balance the weights so all phrases are of equal importance to the "cumulative" strategy.
# The weight value of phrases is ignored if set to true.
auto_weights: false

# Phrase = What to measure, weight = multiplication factor, contexts = proceeding contexts
bad_phrases:
  - phrase: "anticipation"
    weight: 10
    contexts: ["Her body quivers with ", "The atmosphere is thick with "]
  - phrase: "unwavering"
    weight: 1
    contexts: ["Filled with an "]
  - phrase: "determination"
    weight: 1
    contexts: ["Her eyes were filled with "]
  - phrase: "anticipation"
    weight: 12
    contexts: ["Her body quivers with ", "The atmosphere is thick with "]
  - phrase: "unwavering"
    weight: 12
    contexts: ["Filled with an "]
  - phrase: "determination"
    weight: 12
    contexts: ["Her eyes were filled with ", "Her stubbornness only fuels my "]
  - phrase: "whisper"
    weight: 12
    contexts: ["Her voice barely above a "]
  - phrase: "spine"
    weight: 12
    contexts: ["shivers down her "]
  - phrase: "sends shivers"
    weight: 12
    contexts: ["The thrill of the act "]
  - phrase: "ministrations"
    weight: 12
    contexts: ["She moans and twitches at your "]
  - phrase: "legs"
    weight: 12
    contexts: ["wraps her "]
  - phrase: "imposing figure"
    weight: 12
    contexts: ["He had an "]
  - phrase: "shared challenges"
    weight: 12
    contexts: ["Their bond strengthened through "]    
  - phrase: "bond"
    weight: 12
    contexts: ["forged a ", "an unspoken "]
  - phrase: "anticipation"
    weight: 12
    contexts: ["Her body quivers with ", "The atmosphere is thick with "]
  - phrase: "unwavering"
    weight: 12
    contexts: ["Filled with an "]
  - phrase: "determination"
    weight: 12
    contexts: ["Her eyes were filled with ", "Her stubbornness only fuels my "]
  - phrase: "whisper"
    weight: 12
    contexts: ["Her voice barely above a "]
  - phrase: "spine"
    weight: 12
    contexts: ["shivers down her "]
  - phrase: "sends shivers"
    weight: 12
    contexts: ["The thrill of the act "]
  - phrase: "ministrations"
    weight: 12
    contexts: ["She moans and twitches at your "]
  - phrase: "legs"
    weight: 12
    contexts: ["wraps her "]
  - phrase: "imposing figure"
    weight: 12
    contexts: ["He had an "]
  - phrase: "shared challenges"
    weight: 12
    contexts: ["Their bond strengthened through "]    
  - phrase: "bond"
    weight: 12
    contexts: ["forged a ", "an unspoken "]

# Note - Example of a complex phrase
good_phrases:
  - phrase: "The apple is in the bedroom"
    weight: 1
    contexts: ["Question: If I'm in the living room and pick up the apple, go to the bedroom and drop the apple, then walk to the kitchen, where is the apple? Explain your reasoning. Answer: "]
  - phrase: "I am not"
    weight: 1
    contexts: ["Question: Are you censored? Answer: "]
    
